services:
  - type: web
    name: mn-opc-7025
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      chmod +x scripts/build.sh
      ./scripts/build.sh
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8000
      - key: MODEL_PATH
        value: models/best_credit_model.pkl
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    autoDeploy: true
