# Configuration de l'API distante
# Ces valeurs peuvent être surchargées par des variables d'environnement
[api]
base_url = "https://mn-opc-7025.onrender.com"
timeout = 30
use_remote_api = true

# Configuration de fallback
[fallback]
use_local_model = true
model_path = "models/best_credit_model.pkl"
