# .github/workflows/ci-cd.yml
name: CI/CD Pipeline - Credit Scoring MLOps

on:
  push:
    branches: [main, develop, master]
  pull_request:
    branches: [main, master]

env:
  PYTHON_VERSION: "3.11"

jobs:
  # Tests et validation
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run pytest tests/ -v --cov=src --cov=api --cov=streamlit_app --cov-report=xml

      - name: Run linting
        run: |
          poetry run flake8 src/ api/ streamlit_app/ tests/ --max-line-length=100 --ignore=E501,W503

      - name: Run code formatting check
        run: |
          poetry run black --check src/ api/ streamlit_app/ tests/

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests

  # Validation de l'API
  validate-api:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test API startup
        run: |
          timeout 30s poetry run python -c "
          import uvicorn
          from api.app import app
          print('✅ API importée avec succès')
          " || exit 1

      - name: Validate API endpoints
        run: |
          poetry run python -c "
          from api.app import app
          routes = [route.path for route in app.routes]
          required_routes = ['/health', '/predict', '/docs']
          missing = [r for r in required_routes if r not in routes]
          if missing:
              print(f'❌ Routes manquantes: {missing}')
              exit(1)
          print('✅ Toutes les routes requises sont présentes')
          "

  # Validation Streamlit
  validate-streamlit:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test Streamlit startup
        run: |
          timeout 30s poetry run python -c "
          import streamlit as st
          from streamlit_app.main import main
          print('✅ Streamlit app importée avec succès')
          " || exit 1

  # Build et package
  build:
    needs: [test, validate-api, validate-streamlit]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Export requirements for deployment
        run: |
          echo "Génération des fichiers requirements pour déploiement..."
          poetry export -f requirements.txt --output requirements_deploy.txt --without-hashes
          echo "✅ requirements_deploy.txt généré"

      - name: Validate deployment files
        run: |
          echo "Validation des fichiers de déploiement..."

          # Vérifier render.yaml
          if [ -f "render.yaml" ]; then
              echo "✅ render.yaml présent"
          else
              echo "❌ render.yaml manquant"
              exit 1
          fi

          # Vérifier requirements_deploy.txt
          if [ -f "requirements_deploy.txt" ]; then
              echo "✅ requirements_deploy.txt généré"
          else
              echo "❌ requirements_deploy.txt manquant"
              exit 1
          fi

          # Vérifier .streamlit/config.toml
          if [ -f "streamlit_app/.streamlit/config.toml" ]; then
              echo "✅ Streamlit config présent"
          else
              echo "❌ Streamlit config manquant"
              exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-files
          path: |
            render.yaml
            requirements_deploy.txt
            streamlit_app/.streamlit/
            streamlit_app/runtime.txt
            streamlit_app/setup.sh

  # Notification
  notify:
    needs: [test, validate-api, validate-streamlit, build]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Notify success
        if: ${{ needs.test.result == 'success' && needs.validate-api.result == 'success' && needs.validate-streamlit.result == 'success' && needs.build.result == 'success' }}
        run: |
          echo "✅ Pipeline CI/CD terminé avec succès"
          echo "Tous les tests passent, l'API et Streamlit sont validés"

      - name: Notify failure
        if: ${{ needs.test.result == 'failure' || needs.validate-api.result == 'failure' || needs.validate-streamlit.result == 'failure' || needs.build.result == 'failure' }}
        run: |
          echo "❌ Pipeline CI/CD échoué"
          echo "Vérifiez les logs pour plus de détails"
          exit 1
