name: Deploy API to HuggingFace Space

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'models/**'
      - 'requirements_minimal.txt'
      - 'tools/push_to_hf.py'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uploader deps
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Upload API to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_API }}
          HF_SPACE_ID: Kodezar/opcmne7p-api
          COMPONENT: api
        run: |
          python tools/push_to_hf.py
