name: Rules CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  rules-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade pip pyyaml

      - name: Rules meta lint
        run: python docs/scripts/rules_meta_lint.py

      - name: Scan adapters duplication
        run: bash docs/scripts/scan_adapters_dup.sh

