name: Test et Validation de Streamlit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installation des dépendances Streamlit
        run: |
          python -m pip install --upgrade pip
          pip install -r streamlit_app/requirements.txt

      - name: Validation de la syntaxe Streamlit
        run: |
          python -m py_compile streamlit_app/main.py
          python -c "import streamlit_app.main; print('✅ Streamlit importé avec succès')"

      - name: Test de démarrage Streamlit (headless)
        run: |
          timeout 30s streamlit run streamlit_app/main.py --server.headless true --server.port 8501 &
          sleep 10
          curl -f http://localhost:8501 || exit 1
