name: Test et Validation de l'API

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_minimal.txt
          pip install pytest pytest-asyncio httpx

      - name: Tests de l'API
        run: |
          python -m pytest tests/api/ -v

      - name: Validation de la syntaxe
        run: |
          python -m py_compile api/app.py
          python -c "import api.app; print('✅ API importée avec succès')"

      - name: Test de démarrage de l'API
        run: |
          timeout 30s uvicorn api.app:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl -f http://localhost:8000/health || exit 1
